### ISSUE TITLE
btsfeed tool error after latest git pull

### ISSUE THREAD

**Issue by bitcoiners** [bitsuperlab/operation_tools#6]
2015-05-17 13:51:08,340[ERROR]: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "./bts_feed_auto.py", line 199, in <module>
    fetch_price()
  File "./bts_feed_auto.py", line 100, in fetch_price
    price_depth["bts_usd"] = client.get_depth_in_range("USD","BTS", depth_change)
  File "/home/tools/local/operation_tools/btsfeed/bts.py", line 66, in get_depth_in_range
    price = self.get_price(quote,base)
  File "/home/tools/local/operation_tools/btsfeed/bts.py", line 256, in get_price
    order = response.json()["result"]
  File "/usr/lib/python3/dist-packages/requests/models.py", line 756, in json
    return json.loads(self.content.decode(encoding), **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 501, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 393, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by bitcoiners** [comment]
Any updates for this bug?
